// Generated by Wrangler on Fri Mar 15 2024 16:57:57 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	ENVIRONMENT: string;
	LINQEM_DB: D1Database;
}
